# Generated by Django 3.0.14 on 2023-02-08 04:36

import blog.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0002_auto_20230208_0341'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='password',
            field=models.TextField(validators=[blog.models.validate_password]),
        ),
    ]
